// dataBahanAjar.js - Dummy Data SITTA (Sistem Informasi Tata Kelola Bahan Ajar)

const dataBahanAjar = [
  {
    kode: "EKMA4111",
    judul: "Pengantar Bisnis",
    penulis: "Dr. Ahmad Fauzi",
    stok: 120,
    satuan: "eksemplar",
    status: "tersedia",
    fakultas: "FE",
    edisi: 2,
  },
  {
    kode: "EKMA4210",
    judul: "Akuntansi Keuangan",
    penulis: "Prof. Siti Rahayu",
    stok: 0,
    satuan: "eksemplar",
    status: "habis",
    fakultas: "FE",
    edisi: 3,
  },
  {
    kode: "MKDU4110",
    judul: "Bahasa Indonesia",
    penulis: "Dr. Bambang Wijaya",
    stok: 45,
    satuan: "eksemplar",
    status: "tersedia",
    fakultas: "MKDU",
    edisi: 1,
  },
  {
    kode: "MSIM4301",
    judul: "Sistem Informasi Manajemen",
    penulis: "Dr. Rina Susanti",
    stok: 8,
    satuan: "eksemplar",
    status: "hampir habis",
    fakultas: "FMIPA",
    edisi: 2,
  },
  {
    kode: "HKUM4301",
    judul: "Hukum Perdata",
    penulis: "Dr. Lukman Hakim",
    stok: 200,
    satuan: "eksemplar",
    status: "tersedia",
    fakultas: "FHISIP",
    edisi: 4,
  },
  {
    kode: "PDGK4101",
    judul: "Keterampilan Menulis",
    penulis: "Dr. Dewi Lestari",
    stok: 15,
    satuan: "eksemplar",
    status: "hampir habis",
    fakultas: "FKIP",
    edisi: 1,
  },
];

const dataTrackingDO = [
  {
    noDO: "DO-2025-001",
    tanggal: "2025-01-10",
    tujuan: "UPBJJ Bandung",
    kode: "EKMA4111",
    judul: "Pengantar Bisnis",
    jumlah: 50,
    status: "terkirim",
    ekspedisi: "JNE",
    noResi: "JNE1234567890",
    estimasiTiba: "2025-01-13",
    aktualTiba: "2025-01-12",
  },
  {
    noDO: "DO-2025-002",
    tanggal: "2025-01-12",
    tujuan: "UPBJJ Surabaya",
    kode: "MKDU4110",
    judul: "Bahasa Indonesia",
    jumlah: 30,
    status: "dalam perjalanan",
    ekspedisi: "TIKI",
    noResi: "TIKI9876543210",
    estimasiTiba: "2025-01-16",
    aktualTiba: null,
  },
  {
    noDO: "DO-2025-003",
    tanggal: "2025-01-14",
    tujuan: "UPBJJ Medan",
    kode: "HKUM4301",
    judul: "Hukum Perdata",
    jumlah: 75,
    status: "diproses",
    ekspedisi: "Pos Indonesia",
    noResi: null,
    estimasiTiba: "2025-01-20",
    aktualTiba: null,
  },
  {
    noDO: "DO-2025-004",
    tanggal: "2025-01-08",
    tujuan: "UPBJJ Makassar",
    kode: "MSIM4301",
    judul: "Sistem Informasi Manajemen",
    jumlah: 20,
    status: "terkirim",
    ekspedisi: "JNT",
    noResi: "JNT1122334455",
    estimasiTiba: "2025-01-15",
    aktualTiba: "2025-01-15",
  },
  {
    noDO: "DO-2025-005",
    tanggal: "2025-01-15",
    tujuan: "UPBJJ Yogyakarta",
    kode: "PDGK4101",
    judul: "Keterampilan Menulis",
    jumlah: 10,
    status: "pending",
    ekspedisi: "-",
    noResi: null,
    estimasiTiba: null,
    aktualTiba: null,
  },
];
